2023/03/29 08:07:10 [emerg] 1#1: bind() to 0.0.0.0:443 failed (13: Permission denied)
2023/03/29 08:08:11 [error] 39#39: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.10.2:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).PHP message: [info] Matched route "app_home".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleAwareListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::configureLogoutUrlGenerator".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Knp\Bundle\PaginatorBundle\Subscriber\SlidingPaginationSubscriber::onKernelRequest".PHP message: [debug] Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".PHP message: [debug] Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataColl
2023/03/29 08:08:14 [error] 39#39: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.10.2:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).PHP message: [info] Matched route "app_api_category_index".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleAwareListener::onKernelRequest".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::configureLogoutUrlGenerator".PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelRequest".PHP message: [critical] Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in the driver: SQLSTATE[HY000] [1130] Host '10.89.1.38' is not allowed to connect to this MariaDB server" at /symfony/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 117PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\
2023/03/29 08:08:14 [error] 39#39: *5 FastCGI sent in stderr: " [debug] Listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onKernelException" stopped propagation of the event "kernel.exception".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelResponse".PHP message: [debug] Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelResponse".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\CacheAttributeListener::onKernelResponse".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::removeCspHeader".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\DisallowRobotsIndexingListener::onResponse".PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse".PHP message: [debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".PHP message: [debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".PHP message: [debug] Notified event "kernel.finish_request" to listener "Symfony\WebpackEncoreBundle\EventListener\ResetAssetsEventListener::resetAssets".PHP message: [debug] Notifi
2023/03/29 08:18:00 [error] 37#37: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.38:8000", host: "172.16.26.136"
2023/03/29 08:18:00 [error] 37#37: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.38:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:19:35 [error] 39#39: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.38:8000", host: "172.16.26.136"
2023/03/29 08:19:35 [error] 39#39: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.38:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:19:37 [error] 39#39: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.38:8000", host: "172.16.26.136"
2023/03/29 08:19:37 [error] 39#39: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.38:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:41:06 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136"
2023/03/29 08:41:09 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:41:09 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136"
2023/03/29 08:41:12 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:41:54 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136"
2023/03/29 08:41:54 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136"
2023/03/29 08:41:57 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136"
2023/03/29 08:42:01 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136"
2023/03/29 08:42:04 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136"
2023/03/29 08:42:07 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136"
2023/03/29 08:42:07 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:10 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:13 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:16 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:16 [error] 37#37: *3 no live upstreams while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://symfony", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:18 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136"
2023/03/29 08:42:21 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136"
2023/03/29 08:42:21 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136"
2023/03/29 08:42:24 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136"
2023/03/29 08:42:27 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136"
2023/03/29 08:42:30 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136"
2023/03/29 08:42:33 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:41 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136"
2023/03/29 08:42:44 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136"
2023/03/29 08:42:47 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136"
2023/03/29 08:42:50 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136"
2023/03/29 08:42:50 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136"
2023/03/29 08:42:53 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136"
2023/03/29 08:42:56 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:42:59 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:02 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:02 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:06 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:09 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:22 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136"
2023/03/29 08:43:22 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136"
2023/03/29 08:43:25 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136"
2023/03/29 08:43:28 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136"
2023/03/29 08:43:31 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136"
2023/03/29 08:43:34 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136"
2023/03/29 08:43:37 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.54:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:37 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.61:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:40 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.57:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:43 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.59:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:47 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.60:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:43:50 [error] 37#37: *3 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.58:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 08:49:05 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.3:8000", host: "172.16.26.136"
2023/03/29 08:49:05 [error] 37#37: *3 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://10.89.1.3:8000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
2023/03/29 09:22:31 [error] 35#35: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.10:8000", host: "172.16.26.136"
2023/03/29 09:24:38 [error] 38#38: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.10:9000", host: "172.16.26.136"
2023/03/29 09:24:41 [error] 38#38: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.10:9000", host: "172.16.26.136"
2023/03/29 10:41:05 [emerg] 1#1: host not found in upstream "symfony" in /opt/bitnami/nginx/conf/server_blocks/server.conf:32
2023/03/29 10:45:04 [error] 37#37: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.22:9000", host: "172.16.26.136"
2023/03/29 10:49:43 [error] 38#38: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.10.2, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://10.89.1.26:9000", host: "172.16.26.136"
2023/03/29 11:28:14 [error] 36#36: *2 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.10.2, server: _, request: "GET /api/category?limit=6 HTTP/2.0", upstream: "fastcgi://10.89.1.52:9000", host: "172.16.26.136", referrer: "https://172.16.26.136/"
